import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/db';
import { reports } from '@/db/schema';
import { requireMobileAuth } from '@/lib/utils/session';
import { desc, eq } from 'drizzle-orm';

// GET /api/mobile/reports
// Returns all reports generated by the authenticated technician
export async function GET(request: NextRequest) {
    try {
        const user = await requireMobileAuth();

        const { searchParams } = new URL(request.url);
        const type = searchParams.get('type'); // optional filter: trip | snow | attendance

        const allReports = await db.query.reports.findMany({
            where: type ? eq(reports.type, type) : undefined,
            orderBy: [desc(reports.createdAt)],
        });

        // Filter to only this technician's reports
        const userReports = allReports.filter(r => r.generatedBy === user.id);

        return NextResponse.json({ reports: userReports });
    } catch (error: any) {
        if (error.message === 'Unauthorized') {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }
        console.error('Mobile reports error:', error);
        return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }
}
